### ISSUE TITLE
Move dummy data functions back to main package

### ISSUE THREAD

**Issue by lazappi** [scverse/anndataR#136]
It would be helpful to have the dummy data functions accessible from the main package, not just the tests. Mainly, this would be useful for examples so that they are shorter, more consistent and easier to write.

**Comment by rcannood** [comment]
PR #107 contains generator functions which are more thorough than the dummy_data functions: https://github.com/scverse/anndataR/pull/107/files#diff-0a53e9410969c293b7cb779571e4214869cfc85747d19f82709a87aa44657785R17
Unfortunately, since the `generate_dataset()` generates objects with many more data types, the unit tests don't work anymore :sweat_smile: 


However, I'm not inclined on exporting these functions so users can use these functions, because it distracts from the functionality that anndataR is trying to provide. In the examples, I think it's actually useful to showcase how to create AnnData objects from scratch instead of using a generator function.

However, if you feel strongly about this, we can look into exporting this function again.

**Comment by lazappi** [comment]
Ok, I'll have a look at those. I actually think it makes the examples much clearer if you just have the function you are demonstrating without a big chunk of code creating an object first.

What I do feel very strongly about is not showing users the AnnData objects at all but I want to discuss that at the next meeting.
